# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_demo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
# 以下4行是手动添加的
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas 
from matplotlib.backends.backend_qt5 import NavigationToolbar2QT as NavigationToolbar 
import matplotlib.pyplot as plt 
import numpy as np 

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1191, 686)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(331, 0))
        self.frame.setMaximumSize(QtCore.QSize(331, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_RGB = QtWidgets.QFrame(self.frame)
        self.frame_RGB.setMinimumSize(QtCore.QSize(311, 111))
        self.frame_RGB.setMaximumSize(QtCore.QSize(311, 111))
        self.frame_RGB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RGB.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_RGB.setObjectName("frame_RGB")
        self.frame_RGB_quyu = QtWidgets.QFrame(self.frame_RGB)
        self.frame_RGB_quyu.setGeometry(QtCore.QRect(180, 10, 121, 91))
        self.frame_RGB_quyu.setMinimumSize(QtCore.QSize(121, 91))
        self.frame_RGB_quyu.setMaximumSize(QtCore.QSize(121, 91))
        self.frame_RGB_quyu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RGB_quyu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_RGB_quyu.setObjectName("frame_RGB_quyu")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_RGB_quyu)
        self.gridLayout_5.setObjectName("gridLayout_5")
        # 以下4行是手动修改的，用来显示调色板颜色的控件
        self.figure2, self.figaxes2 = plt.subplots()
        self.figure2.subplots_adjust(left=0.0,top=1.0,right=1.0,bottom=0.0)
        self.canvas2 = FigureCanvas(self.figure2)
        self.gridLayout_5.addWidget(self.canvas2, 0, 0, 1, 1)

        self.layoutWidget = QtWidgets.QWidget(self.frame_RGB)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.RGB_R_slider = QtWidgets.QSlider(self.layoutWidget)
        self.RGB_R_slider.setMaximum(255)
        self.RGB_R_slider.setPageStep(1)
        self.RGB_R_slider.setProperty("value", 255)
        self.RGB_R_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RGB_R_slider.setObjectName("RGB_R_slider")
        self.horizontalLayout.addWidget(self.RGB_R_slider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.RGB_G_slider = QtWidgets.QSlider(self.layoutWidget)
        self.RGB_G_slider.setMaximum(255)
        self.RGB_G_slider.setPageStep(1)
        self.RGB_G_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RGB_G_slider.setObjectName("RGB_G_slider")
        self.horizontalLayout_2.addWidget(self.RGB_G_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.RGB_B_slider = QtWidgets.QSlider(self.layoutWidget)
        self.RGB_B_slider.setMaximum(255)
        self.RGB_B_slider.setPageStep(1)
        self.RGB_B_slider.setOrientation(QtCore.Qt.Horizontal)
        self.RGB_B_slider.setObjectName("RGB_B_slider")
        self.horizontalLayout_3.addWidget(self.RGB_B_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.RGB_R_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.RGB_R_spinBox.setMaximum(255)
        self.RGB_R_spinBox.setProperty("value", 255)
        self.RGB_R_spinBox.setObjectName("RGB_R_spinBox")
        self.verticalLayout_2.addWidget(self.RGB_R_spinBox)
        self.RGB_G_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.RGB_G_spinBox.setMaximum(255)
        self.RGB_G_spinBox.setObjectName("RGB_G_spinBox")
        self.verticalLayout_2.addWidget(self.RGB_G_spinBox)
        self.RGB_B_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.RGB_B_spinBox.setMaximum(255)
        self.RGB_B_spinBox.setObjectName("RGB_B_spinBox")
        self.verticalLayout_2.addWidget(self.RGB_B_spinBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addWidget(self.frame_RGB, 0, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.frame)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 309, 407))
        self.page.setObjectName("page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_type = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_type.setGeometry(QtCore.QRect(10, 50, 69, 22))
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.frame_wenzi = QtWidgets.QFrame(self.frame_3)
        self.frame_wenzi.setGeometry(QtCore.QRect(10, 80, 271, 171))
        self.frame_wenzi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_wenzi.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_wenzi.setObjectName("frame_wenzi")
        self.label_7 = QtWidgets.QLabel(self.frame_wenzi)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 41, 21))
        self.label_7.setObjectName("label_7")
        self.putText = QtWidgets.QLineEdit(self.frame_wenzi)
        self.putText.setGeometry(QtCore.QRect(60, 10, 191, 20))
        self.putText.setObjectName("putText")
        self.label_8 = QtWidgets.QLabel(self.frame_wenzi)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 41, 21))
        self.label_8.setObjectName("label_8")
        self.putText_ziti = QtWidgets.QComboBox(self.frame_wenzi)
        self.putText_ziti.setGeometry(QtCore.QRect(60, 70, 161, 22))
        self.putText_ziti.setObjectName("putText_ziti")
        self.putText_ziti.addItem("")
        self.label_16 = QtWidgets.QLabel(self.frame_wenzi)
        self.label_16.setGeometry(QtCore.QRect(20, 100, 41, 21))
        self.label_16.setObjectName("label_16")
        self.putText_daxiao = QtWidgets.QSpinBox(self.frame_wenzi)
        self.putText_daxiao.setGeometry(QtCore.QRect(60, 100, 82, 20))
        self.putText_daxiao.setMinimumSize(QtCore.QSize(82, 20))
        self.putText_daxiao.setMaximumSize(QtCore.QSize(82, 20))
        self.putText_daxiao.setMaximum(999999999)
        self.putText_daxiao.setProperty("value", 1)
        self.putText_daxiao.setObjectName("putText_daxiao")
        self.label_17 = QtWidgets.QLabel(self.frame_wenzi)
        self.label_17.setGeometry(QtCore.QRect(20, 130, 61, 21))
        self.label_17.setObjectName("label_17")
        self.putText_type = QtWidgets.QComboBox(self.frame_wenzi)
        self.putText_type.setGeometry(QtCore.QRect(90, 130, 101, 22))
        self.putText_type.setObjectName("putText_type")
        self.putText_type.addItem("")
        self.putText_type.addItem("")
        self.putText_type.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_wenzi)
        self.label_15.setGeometry(QtCore.QRect(20, 40, 41, 21))
        self.label_15.setObjectName("label_15")
        self.putText_x = QtWidgets.QSpinBox(self.frame_wenzi)
        self.putText_x.setGeometry(QtCore.QRect(60, 40, 82, 20))
        self.putText_x.setMinimumSize(QtCore.QSize(82, 20))
        self.putText_x.setMaximumSize(QtCore.QSize(82, 20))
        self.putText_x.setMaximum(999999999)
        self.putText_x.setProperty("value", 100)
        self.putText_x.setObjectName("putText_x")
        self.putText_y = QtWidgets.QSpinBox(self.frame_wenzi)
        self.putText_y.setGeometry(QtCore.QRect(140, 40, 82, 20))
        self.putText_y.setMinimumSize(QtCore.QSize(82, 20))
        self.putText_y.setMaximumSize(QtCore.QSize(82, 20))
        self.putText_y.setMaximum(999999999)
        self.putText_y.setProperty("value", 100)
        self.putText_y.setObjectName("putText_y")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(90, 50, 54, 21))
        self.label_4.setObjectName("label_4")
        self.OK_Btn = QtWidgets.QPushButton(self.frame_3)
        self.OK_Btn.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.OK_Btn.setObjectName("OK_Btn")
        self.spinBox_linetype = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_linetype.setGeometry(QtCore.QRect(150, 50, 42, 22))
        self.spinBox_linetype.setMinimum(-1)
        self.spinBox_linetype.setProperty("value", -1)
        self.spinBox_linetype.setObjectName("spinBox_linetype")
        self.frame_line_range = QtWidgets.QFrame(self.frame_3)
        self.frame_line_range.setGeometry(QtCore.QRect(10, 80, 271, 71))
        self.frame_line_range.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_line_range.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_line_range.setObjectName("frame_line_range")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_line_range)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 10, 216, 52))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.line_range_x_start = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.line_range_x_start.setMinimumSize(QtCore.QSize(82, 20))
        self.line_range_x_start.setMaximumSize(QtCore.QSize(82, 20))
        self.line_range_x_start.setMaximum(999999999)
        self.line_range_x_start.setProperty("value", 20)
        self.line_range_x_start.setObjectName("line_range_x_start")
        self.horizontalLayout_5.addWidget(self.line_range_x_start)
        self.line_range_y_start = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.line_range_y_start.setMinimumSize(QtCore.QSize(82, 20))
        self.line_range_y_start.setMaximumSize(QtCore.QSize(82, 20))
        self.line_range_y_start.setMaximum(999999999)
        self.line_range_y_start.setProperty("value", 20)
        self.line_range_y_start.setObjectName("line_range_y_start")
        self.horizontalLayout_5.addWidget(self.line_range_y_start)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.line_range_x_stop = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.line_range_x_stop.setMinimumSize(QtCore.QSize(82, 20))
        self.line_range_x_stop.setMaximumSize(QtCore.QSize(82, 20))
        self.line_range_x_stop.setMaximum(999999999)
        self.line_range_x_stop.setProperty("value", 100)
        self.line_range_x_stop.setObjectName("line_range_x_stop")
        self.horizontalLayout_6.addWidget(self.line_range_x_stop)
        self.line_range_y_stop = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.line_range_y_stop.setMinimumSize(QtCore.QSize(82, 20))
        self.line_range_y_stop.setMaximumSize(QtCore.QSize(82, 20))
        self.line_range_y_stop.setMaximum(999999999)
        self.line_range_y_stop.setProperty("value", 200)
        self.line_range_y_stop.setObjectName("line_range_y_stop")
        self.horizontalLayout_6.addWidget(self.line_range_y_stop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.frame_yuan = QtWidgets.QFrame(self.frame_3)
        self.frame_yuan.setGeometry(QtCore.QRect(10, 80, 271, 71))
        self.frame_yuan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_yuan.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_yuan.setObjectName("frame_yuan")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_yuan)
        self.layoutWidget_3.setGeometry(QtCore.QRect(22, 12, 214, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.yuanxin_x = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.yuanxin_x.setMinimumSize(QtCore.QSize(82, 20))
        self.yuanxin_x.setMaximumSize(QtCore.QSize(82, 20))
        self.yuanxin_x.setMaximum(999999999)
        self.yuanxin_x.setProperty("value", 123)
        self.yuanxin_x.setObjectName("yuanxin_x")
        self.horizontalLayout_7.addWidget(self.yuanxin_x)
        self.yuanxin_y = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.yuanxin_y.setMinimumSize(QtCore.QSize(82, 20))
        self.yuanxin_y.setMaximumSize(QtCore.QSize(82, 20))
        self.yuanxin_y.setMaximum(999999999)
        self.yuanxin_y.setProperty("value", 123)
        self.yuanxin_y.setObjectName("yuanxin_y")
        self.horizontalLayout_7.addWidget(self.yuanxin_y)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_yuan)
        self.layoutWidget_4.setGeometry(QtCore.QRect(22, 40, 126, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.yuan_banjing = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.yuan_banjing.setMinimumSize(QtCore.QSize(82, 20))
        self.yuan_banjing.setMaximumSize(QtCore.QSize(82, 20))
        self.yuan_banjing.setMaximum(999999999)
        self.yuan_banjing.setProperty("value", 33)
        self.yuan_banjing.setObjectName("yuan_banjing")
        self.horizontalLayout_8.addWidget(self.yuan_banjing)
        self.frame_tuoyuan = QtWidgets.QFrame(self.frame_3)
        self.frame_tuoyuan.setGeometry(QtCore.QRect(10, 80, 271, 131))
        self.frame_tuoyuan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tuoyuan.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_tuoyuan.setObjectName("frame_tuoyuan")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_tuoyuan)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 10, 228, 108))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.zhongxindian_x = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.zhongxindian_x.setMinimumSize(QtCore.QSize(82, 20))
        self.zhongxindian_x.setMaximumSize(QtCore.QSize(82, 20))
        self.zhongxindian_x.setMaximum(999999999)
        self.zhongxindian_x.setProperty("value", 160)
        self.zhongxindian_x.setObjectName("zhongxindian_x")
        self.horizontalLayout_9.addWidget(self.zhongxindian_x)
        self.zhongxindian_y = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.zhongxindian_y.setMinimumSize(QtCore.QSize(82, 20))
        self.zhongxindian_y.setMaximumSize(QtCore.QSize(82, 20))
        self.zhongxindian_y.setMaximum(999999999)
        self.zhongxindian_y.setProperty("value", 160)
        self.zhongxindian_y.setObjectName("zhongxindian_y")
        self.horizontalLayout_9.addWidget(self.zhongxindian_y)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.changzhou = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.changzhou.setMinimumSize(QtCore.QSize(82, 20))
        self.changzhou.setMaximumSize(QtCore.QSize(82, 20))
        self.changzhou.setMaximum(999999999)
        self.changzhou.setProperty("value", 100)
        self.changzhou.setObjectName("changzhou")
        self.horizontalLayout_10.addWidget(self.changzhou)
        self.duanzhou = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.duanzhou.setMinimumSize(QtCore.QSize(82, 20))
        self.duanzhou.setMaximumSize(QtCore.QSize(82, 20))
        self.duanzhou.setMaximum(999999999)
        self.duanzhou.setProperty("value", 50)
        self.duanzhou.setObjectName("duanzhou")
        self.horizontalLayout_10.addWidget(self.duanzhou)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.jiaodu = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.jiaodu.setMinimumSize(QtCore.QSize(82, 20))
        self.jiaodu.setMaximumSize(QtCore.QSize(82, 20))
        self.jiaodu.setMaximum(360)
        self.jiaodu.setObjectName("jiaodu")
        self.horizontalLayout_11.addWidget(self.jiaodu)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.jiaodu_start = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.jiaodu_start.setMinimumSize(QtCore.QSize(82, 20))
        self.jiaodu_start.setMaximumSize(QtCore.QSize(82, 20))
        self.jiaodu_start.setMaximum(360)
        self.jiaodu_start.setObjectName("jiaodu_start")
        self.horizontalLayout_12.addWidget(self.jiaodu_start)
        self.jiaodu_end = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.jiaodu_end.setMinimumSize(QtCore.QSize(82, 20))
        self.jiaodu_end.setMaximumSize(QtCore.QSize(82, 20))
        self.jiaodu_end.setMaximum(360)
        self.jiaodu_end.setProperty("value", 360)
        self.jiaodu_end.setObjectName("jiaodu_end")
        self.horizontalLayout_12.addWidget(self.jiaodu_end)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.gridLayout_6.addWidget(self.frame_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 309, 407))
        self.page_2.setObjectName("page_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.widget1 = QtWidgets.QWidget(self.frame_4)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.widget1)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.radioButton = QtWidgets.QRadioButton(self.widget1)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_13.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_13.addWidget(self.radioButton_2)
        self.widget2 = QtWidgets.QWidget(self.frame_4)
        self.widget2.setGeometry(QtCore.QRect(11, 50, 271, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.widget2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_14.addWidget(self.label_20)
        self.lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_14.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(25, 23))
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_14.addWidget(self.pushButton_5)
        self.widget3 = QtWidgets.QWidget(self.frame_4)
        self.widget3.setGeometry(QtCore.QRect(20, 90, 239, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_15.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_4.addWidget(self.toolBox, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
         # 以下7行是手动修改的，用来显示图像和工具的
        self.figure1, self.figaxes1 = plt.subplots()
        # self.yw_figure1.subplots_adjust(left=0.015,top=0.99,right=0.98,bottom=0.015)
        self.canvas1 = FigureCanvas(self.figure1)
        self.toolbar1 = NavigationToolbar(self.canvas1, self.widget)
        self.toolbar1.setMinimumSize(QtCore.QSize(0, 41))
        self.toolbar1.setMaximumSize(QtCore.QSize(16777215, 41))
        self.gridLayout_3.addWidget(self.toolbar1, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.canvas1, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(0)
        self.RGB_B_slider.valueChanged['int'].connect(self.RGB_B_spinBox.setValue)
        self.RGB_B_spinBox.valueChanged['int'].connect(self.RGB_B_slider.setValue)
        self.RGB_G_slider.valueChanged['int'].connect(self.RGB_G_spinBox.setValue)
        self.RGB_G_spinBox.valueChanged['int'].connect(self.RGB_G_slider.setValue)
        self.RGB_R_slider.valueChanged['int'].connect(self.RGB_R_spinBox.setValue)
        self.RGB_R_spinBox.valueChanged['int'].connect(self.RGB_R_slider.setValue)
        self.RGB_R_slider.valueChanged['int'].connect(self.color_board)
        self.RGB_G_slider.valueChanged['int'].connect(self.color_board)
        self.RGB_B_slider.valueChanged['int'].connect(self.color_board)
        self.color_board()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "R:"))
        self.label_2.setText(_translate("Form", "G:"))
        self.label_3.setText(_translate("Form", "B:"))
        self.pushButton.setText(_translate("Form", "打开图像"))
        self.comboBox_type.setItemText(0, _translate("Form", "直线"))
        self.comboBox_type.setItemText(1, _translate("Form", "矩形"))
        self.comboBox_type.setItemText(2, _translate("Form", "圆"))
        self.comboBox_type.setItemText(3, _translate("Form", "椭圆"))
        self.comboBox_type.setItemText(4, _translate("Form", "文字"))
        self.label_7.setText(_translate("Form", "文字："))
        self.putText.setText(_translate("Form", "hello"))
        self.lineEdit.setText(_translate("Form", "D:\\output"))
        self.label_8.setText(_translate("Form", "字体："))
        self.putText_ziti.setItemText(0, _translate("Form", "FONT_HERSHEY_SIMPLEX"))
        self.label_16.setText(_translate("Form", "大小："))
        self.label_17.setText(_translate("Form", "线条类型："))
        self.putText_type.setItemText(0, _translate("Form", "LINE_4"))
        self.putText_type.setItemText(1, _translate("Form", "LINE_8"))
        self.putText_type.setItemText(2, _translate("Form", "LINE_AA"))
        self.label_15.setText(_translate("Form", "位置："))
        self.label_4.setText(_translate("Form", "线条类型："))
        self.OK_Btn.setText(_translate("Form", "确定"))
        self.label_5.setText(_translate("Form", "起点："))
        self.label_6.setText(_translate("Form", "终点："))
        self.label_9.setText(_translate("Form", "圆点："))
        self.label_10.setText(_translate("Form", "半径："))
        self.label_11.setText(_translate("Form", "中心点："))
        self.label_12.setText(_translate("Form", "长短轴："))
        self.label_13.setText(_translate("Form", "旋转角："))
        self.label_14.setText(_translate("Form", "始终角："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "绘图"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"right\">视频方式：</p></body></html>"))
        self.radioButton.setText(_translate("Form", "摄像头"))
        self.radioButton_2.setText(_translate("Form", "视频文件"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"right\">视频路径：</p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "..."))
        self.pushButton_2.setText(_translate("Form", "打开视频"))
        self.pushButton_3.setText(_translate("Form", "录制视频"))
        self.pushButton_4.setText(_translate("Form", "关闭"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "视频"))


    def color_board(self):# 这个函数是自己写的，用来显示调色板的颜色，也可以不写在这个文件中
        img = np.zeros((71,101,3), np.uint8)
        r = self.RGB_R_slider.value()
        g = self.RGB_G_slider.value()
        b = self.RGB_B_slider.value()
        img[:] = [r,g,b]
        self.figaxes2.clear()
        self.showcolor = self.figaxes2.imshow(img)
        self.figaxes2.autoscale_view()
        self.figure2.canvas.draw()
